services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - "1001:2222"
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
  #   depends_on:
  #     - postgres
  #     - mailhog
  #   env_file:
  #     - .env
  #   networks:
  #     - app_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025" # SMTP server
      - "8026:8025" # Web interface
    networks:
      - app_network

  # Uncomment the following to use postgres
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - app_network

volumes:
  data:
  pgdata:
  node_modules:

networks:
  app_network:
    driver: bridge
